# Generated by Django 3.2.8 on 2021-12-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211211_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechatmessage',
            name='message_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
