# Generated by Django 3.2.8 on 2022-01-29 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_privatechatmessage_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechatmessage',
            name='chat_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_message', to='core.privatechatthread'),
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField(blank=True, null=True)),
                ('public_key', models.TextField(blank=True, null=True)),
                ('keys_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
