# Generated by Django 3.2.8 on 2022-01-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220129_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='second_private_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
