# Generated by Django 3.2.8 on 2022-03-07 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_keys_second_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatmessage',
            name='gc_thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gc_message', to='core.groupchatthread'),
        ),
        migrations.CreateModel(
            name='GroupJoinedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('updated_joined_date', models.DateTimeField(auto_now=True)),
                ('gc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gc_joined', to='core.groupchatthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grp_joined_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
